### PR TITLE
Implement deserialization for float types (closes #5)

### LINKED ISSUE #5: Expects `DecodeScalar` for `f32`
Given the following:
```rust
#[derive(Clone, Debug, knuffel::Decode)]
pub struct ManifestNode {
    #[knuffel(child, unwrap(argument))]
    pub version: f32,
}
```

`cargo check`

```
error[E0277]: the trait bound `f32: DecodeScalar<S>` is not satisfied
 --> backend/src/manifest.rs:9:24
  |
9 | #[derive(Clone, Debug, knuffel::Decode)]
  |                        ^^^^^^^^^^^^^^^ the trait `DecodeScalar<S>` is not implemented for `f32`
```

Why is this?

### PR DESCRIPTION
**Pull request by spikespaz**
I'm not sure if this is complete, but it should be as far as I can tell.

### CODE REVIEW

**Comment by spikespaz** [comment]
This probably needs new tests, I have just tested it with `[patch]` on my project.

**Review by tailhook — COMMENTED** [review]
Looks good, few little things:
1. I'd prefer `impl_integer`, `impl_decimal` as separate macros. The code duplication there isn't a big issue. But reading flow control of the macros is not trivial.
2. Yes, please add some tests. I think adding few fields to `derive/tests/scalars.rs` should be fine. Two variations needed:
    1. Check that integers are good floating point values too
    2. Test with explicit type in KDL document

**Comment by pingiun** [comment]
I was just running into this issue myself, hope it can get merged!

**Comment by gamma-delta** [comment]
Bump on this? It seems like a bit of a silly thing to not have ...

**Comment by spikespaz** [comment]
This is missing tests. I forgot how it works by now, but it should be trivial for the maintainer to either close this and make the changes, or merge it and add tests.

I have stopped using Knuffel.

**Comment by tailhook** [comment]
Superseded by #24. Sorry for the long delay.

**Pull request closed without merging**
